In [1]:
import pandas as pd
import numpy as np

In [2]:
movies_ratings = pd.read_csv(r"C:\Users\abhin\Downloads\ratings.csv",nrows = 1048576)
print(movies_ratings)

         userId  movieId  rating   timestamp
0             1      110     1.0  1425941529
1             1      147     4.5  1425942435
2             1      858     5.0  1425941523
3             1     1221     5.0  1425941546
4             1     1246     5.0  1425941556
...         ...      ...     ...         ...
1048571   10656     1610     3.0   906755296
1048572   10656     1614     3.0   906754185
1048573   10656     1616     1.0   906755479
1048574   10656     1617     4.0   906832779
1048575   10656     1629     3.0   906752725

[1048576 rows x 4 columns]


In [3]:
dup_data = movies_ratings.copy()
print(dup_data)

         userId  movieId  rating   timestamp
0             1      110     1.0  1425941529
1             1      147     4.5  1425942435
2             1      858     5.0  1425941523
3             1     1221     5.0  1425941546
4             1     1246     5.0  1425941556
...         ...      ...     ...         ...
1048571   10656     1610     3.0   906755296
1048572   10656     1614     3.0   906754185
1048573   10656     1616     1.0   906755479
1048574   10656     1617     4.0   906832779
1048575   10656     1629     3.0   906752725

[1048576 rows x 4 columns]


In [4]:
final_dataset = movies_ratings.pivot_table(index = 'userId', columns = 'movieId', values = 'rating').fillna(0)

In [5]:
print(final_dataset)

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     3.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0     0.0     0.0     0.0     0.0     3.0     0.0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
10652       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
10653       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
10654       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
10655       0.0     0.0     0.0     0.0     0.0     4.0     0.0     0.0   
10656       5.0     3.0     0.0     0.0     0.0     4.0     3.0     0.0   

movieId  9       10     

In [6]:
dup_data['rating'] = dup_data['rating'].apply(lambda x: 0 if x > 0 else 1)

In [7]:
dup_final = dup_data.pivot_table(index = 'userId', columns = 'movieId', values = 'rating').fillna(1)
print(dup_final)

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
2           1.0     1.0     1.0     1.0     0.0     1.0     1.0     1.0   
3           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
5           1.0     1.0     1.0     1.0     1.0     1.0     0.0     1.0   
...         ...     ...     ...     ...     ...     ...     ...     ...   
10652       1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
10653       1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
10654       1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
10655       1.0     1.0     1.0     1.0     1.0     0.0     1.0     1.0   
10656       0.0     0.0     1.0     1.0     1.0     0.0     0.0     1.0   

movieId  9       10     

In [8]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(final_dataset)
similarity[np.isnan(similarity)] = 0
print(similarity)

[[1.         0.         0.13953492 ... 0.         0.08038965 0.01850281]
 [0.         1.         0.         ... 0.         0.0280599  0.1555093 ]
 [0.13953492 0.         1.         ... 0.         0.04824977 0.08929525]
 ...
 [0.         0.         0.         ... 1.         0.         0.01776953]
 [0.08038965 0.0280599  0.04824977 ... 0.         1.         0.14866565]
 [0.01850281 0.1555093  0.08929525 ... 0.01776953 0.14866565 1.        ]]


In [9]:
user_predicted_ratings = np.dot(similarity, final_dataset)
print(user_predicted_ratings)

[[6.52156719e+02 2.03122098e+02 5.45800103e+01 ... 2.55196814e-01
  1.82283438e-01 2.10032087e-01]
 [9.37266272e+02 2.62376784e+02 2.82613417e+02 ... 3.62059922e-01
  9.14215377e-02 5.15242459e-02]
 [7.73082811e+02 2.67428952e+02 1.04823151e+02 ... 1.16772905e-01
  8.34092181e-02 1.73461676e-01]
 ...
 [1.37061841e+02 8.82227292e+01 2.54144082e+01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.36238285e+03 5.09015176e+02 1.89069883e+02 ... 8.21868200e-01
  3.56790136e-01 6.77577487e-01]
 [2.06150388e+03 7.55980008e+02 3.84703128e+02 ... 5.86595036e-01
  2.67291797e-01 3.82238253e-01]]


In [10]:
user_final_ratings = np.multiply(user_predicted_ratings,dup_final)
print(user_final_ratings.head())

movieId      1           2           3          4           5       \
userId                                                               
1        652.156719  203.122098   54.580010   9.021225   61.301945   
2        937.266272  262.376784  282.613417  27.890429    0.000000   
3        773.082811  267.428952  104.823151  21.486182  104.523062   
4        791.747546  272.106656  104.391373  17.727403  104.418559   
5        700.581687  206.917124   89.670048  14.930339   86.476159   

movieId      6           7          8          9           10      ...  \
userId                                                             ...   
1        223.922488   67.043753   6.173983  15.792710  194.816206  ...   
2        455.016561  296.955553  17.911715  93.907320  376.698467  ...   
3        294.977399  122.091750  14.065703  28.570124  346.257564  ...   
4        316.312452  122.940384  13.156891  27.006048  294.887250  ...   
5        280.823425    0.000000   9.963173  25.331745  267.727954

In [11]:
user_final_ratings.iloc[26].sort_values(ascending = False)[0:10]

movieId
296     2213.550872
527     1769.898190
480     1669.140018
110     1560.831179
2858    1493.331606
4993    1460.265567
2028    1329.379442
7153    1288.515394
5952    1285.913472
150     1253.821985
Name: 27, dtype: float64